-- MySQL Script generated by MySQL Workbench
-- Thu Dec  6 22:10:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema max
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema max
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `max` DEFAULT CHARACTER SET utf8 ;
USE `max` ;

-- -----------------------------------------------------
-- Table `max`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `max`.`admin` (
  `idadmin` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `max`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `max`.`categoria` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `max`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `max`.`produto` (
  `idproduto` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `datacadastro` DATE NOT NULL,
  `idadmin` INT(11) NOT NULL,
  `idcategoria` INT(11) NOT NULL,
  PRIMARY KEY (`idproduto`),
  INDEX `fk_produto_admin_idx` (`idadmin` ASC),
  INDEX `fk_produto_categoria1_idx` (`idcategoria` ASC),
  CONSTRAINT `fk_produto_admin`
    FOREIGN KEY (`idadmin`)
    REFERENCES `max`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `max`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 66
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `max`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `max`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `max`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `max`.`venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `datavenda` DATE NOT NULL,
  `idcliente` INT NOT NULL,
  PRIMARY KEY (`idvenda`),
  INDEX `fk_Venda_Cliente1_idx` (`idcliente` ASC),
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `max`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `max`.`itensvenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `max`.`itensvenda` (
  `idvenda` INT NOT NULL,
  `idproduto` INT(11) NOT NULL,
  `qtdproduto` INT NOT NULL,
  PRIMARY KEY (`idvenda`, `idproduto`),
  INDEX `fk_Venda_has_produto_produto1_idx` (`idproduto` ASC),
  INDEX `fk_Venda_has_produto_Venda1_idx` (`idvenda` ASC),
  CONSTRAINT `fk_Venda_has_produto_Venda1`
    FOREIGN KEY (`idvenda`)
    REFERENCES `max`.`venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_has_produto_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `max`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
